version: '3.9'

services:
  maqsud:
    container_name: djangoapp
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=localhost
      - DB_NAME=databasa
      - DB_USER=maqsud571
      - DB_PASS=1234
      - PG_PORT=5432
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:12
    environment:
      - POSTGRES_DB=databasa
      - POSTGRES_USER=maqsud571
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data
volumes:
  pgdata: {}


